services:
  - type: web
    name: nodejs-postgresql
    env: node
    repo: https://github.com/geshan/nodejs-posgresql.git
    region: oregon
    branch: master
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: ~20.0.0
      - key: NODE_ENV
        value: production
